version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: "host"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - 80:80
    env_file:
      - .env
    network_mode: "host"

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    network_mode: "host"
